# Generated by Django 6.1.1 on 2026-09-22 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclemovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='vehiclemovement',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='vehiclemovement',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='vehiclemovement',
            name='status',
        ),
        migrations.AddField(
            model_name='vehiclemovement',
            name='movement_type',
            field=models.CharField(default='Entry', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='access_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='EntryExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ENTERED', max_length=20)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
