# Generated by Django 6.1.1 on 2026-09-22 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_rename_phone_number_vehicle_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='vehiclemovement',
            old_name='timestamp',
            new_name='movement_time',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='access_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='movement_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='vehicles.vehicle'),
        ),
        migrations.DeleteModel(
            name='EntryExit',
        ),
    ]
